### ISSUE TITLE
Implement Multipart Uploads

### ISSUE THREAD

**Issue by bonedaddy** [RTradeLtd/s3x#12]
Multipart uploads is proving ab it tricky, namely we need a good way to go about reconstructing the multipart object after having uploaded all parts.

**Comment by xiegeo** [comment]
Is it required for an object to be a single file on ipfs? If not, it only requires us to "reconstruct" when downloading from the gateway.

**Comment by bonedaddy** [comment]
Yea it needs to be a single file on IPFS. That being said however, until the multipart upload is "complete", it can exist on individual chunks.

**Comment by xiegeo** [comment]
I think there are two ways of going about it:
1) Use [go-unixfs](github.com/ipfs/go-unixfs) only. When completing a file, copy over data bytes and rewrite the file from parts.
2) Go under unixfs and build the DAG from uploaded data nodes by hash. This is more efficient but harder to do.

We could try 1 first and move to 2 at a later date.

**Comment by bonedaddy** [comment]
Generally speaking when it comes to development I like starting out with the simplest solution, see how that fares, and then if needed move onto the more complex. I think we should go with your first option for now, and then if need be we can rewrite it later.

One thing however is that we probably need to settle on the exact option before we release, as I doubt we can easily make both options compatible wiht each other.
