### ISSUE TITLE
Enable Redundant Ledger Store

### ISSUE THREAD

**Issue by bonedaddy** [RTradeLtd/s3x#4]
Right now the ledger store is in a local key-value store. However we should have a redundant ledger store, which can be done with [go-ds-crdt](https://github.com/ipfs/go-ds-crdt). We can create a wrapper for the pubsub syncer that uses the `PubSubAPI` from TemporalX.

**Comment by xiegeo** [comment]
https://github.com/ipfs/go-ds-crdt/pull/22#issuecomment-583633015
> go-ds-crdt gets really slow when there are many updates to the same key...

This looks bad if we use crdt to backup ledger with bucket name as key.

**Comment by hsanjuan** [comment]
> [ipfs/go-ds-crdt#22 (comment)](https://github.com/ipfs/go-ds-crdt/pull/22#issuecomment-583633015)
> 
> > go-ds-crdt gets really slow when there are many updates to the same key...
> 
> This looks bad if we use crdt to backup ledger with bucket name as key.

Do benchmark. I think the main issue for the above comment is that the map datastore does not understand namespaces so every query is reading and filtering ALL keys in the store regardless of how well things are namespaced.

**Comment by bonedaddy** [comment]
@xiegeo it might be worth benchmarking it as Hector pointed out. If the performance is sufficient we can use it as the main datastore.

Alternatively we could have an instance of `go-ds-crdt`  as a separate datastore, and a job that runs periodically.to backup the datastore.

If performance is measurably and noticeably slower than we probably need to find another solution.

**Comment by xiegeo** [comment]
Does there already exist any good datastore benchmark collections or libraries?

**Comment by bonedaddy** [comment]
Not sure there might be a benchmark comparing speeds against badger v1 and flatfs but that's it I think, @hsanjuan any idea?

**Comment by hsanjuan** [comment]
So there is https://github.com/ipfs/go-ds-measure which can be used to wrap any datastore. I'd suggest setting up a simulation of whatever workload you will have (i.e. writing repeteadly to the same key and reading the value), and then comparing numbers between go-ds-badger and go-ds-crdt (with badger below).

The most interesting number will be to check for degradation as number of operations grow for the workflow that you are interested in, and to verify if that degradation will ever get to a place where latencies are unacceptable. If you control the peers in your setup, you could always "compact" the crdt dag, eventually as needed.

**Comment by bonedaddy** [comment]
@hsanjuan Thanks for the detailed response. In this case it is assumed operators have full control of nodes so crdt compaction can be looked into.

@xiegeo definitely look into `go-ds-measure` and the crdt compaction, that sounds kind of interesting

**Comment by xiegeo** [comment]
@hsanjuan how to run database compaction? I do not see this feature in go-ds-crdt. Is it writing the full data to a new database?

**Comment by hsanjuan** [comment]
> @hsanjuan how to run database compaction? I do not see this feature in go-ds-crdt. Is it writing the full data to a new database?

Essentially export all the key/value pairs out of the database, and re-import using the Batching function on a clean datastore.

**Comment by xiegeo** [comment]
@hsanjuan Thank you.
