### ISSUE TITLE
gRPC Max Messsage Size Error When Downloading Files Over 4MB In Size Prevents File Transfer

### ISSUE THREAD

**Issue by bonedaddy** [RTradeLtd/s3x#47]
## Expected Behavior
* Be able to download a large file over 4MB in size without running into gRPC message size limitation

## Current Behavior
* Download stops because the we attempt to pull data out of the gRPC API in one call that is larger than the max default message size

## Possible Solution
* Add a Stream based DAG RPC to circumvent this issue for large files (most optimal)
* Don't use DAG RPC directly and instead us the FIleAPI which has stream based RPCs (2nd most optimal)
* Enable configurable max message size as a setting for TemporalX and recomend people set it when using s3x (least optimal)

## Steps to Reproduce (for bugs)

1. Using `mc` command line client upload a file to s3x that is larger than 4MB
2. Download the file
3. Download will be stuck at 0%

## Your Environment

MinIO Version: latest commit from https://github.com/RTradeLtd/s3x/pull/40

MinIO log:

```
temporal@delta-node-2:~$ docker logs 5e0
badger 2020/04/16 08:02:23 INFO: All 0 tables opened in 0s
Endpoint:  http://172.19.0.3:9000  http://127.0.0.1:9000

Browser Access:
   http://172.19.0.3:9000  http://127.0.0.1:9000

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
2020/04/16 08:02:42 bucket-name: bin	bucket-hash: bafkreicdw7cccvqg54qw5424ryaxz5ork6p6sfl6evw7rwowu6ilzqgrti
2020/04/16 08:03:05 bucket-name: bin, object-name: minio, file-hash: bafybeiezdyowoxvhocf5qubogwrdzoowzmjprfi7rl6pe6chomg6xcvpua

API: GetObject(bucket=bin, object=minio)
Time: 08:03:16 UTC 04/16/2020
DeploymentID: 4de3c0fa-4433-411e-ba95-38d53e0cf16e
RequestID: 16063E194454FAC7
RemoteHost: 10.10.10.2
Host: 192.168.1.205:9999
UserAgent: MinIO (linux; amd64) minio-go/v6.0.50 mc/2020-03-14T01:23:37Z
Error: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4194309 vs. 4194304)
       4: /home/solidity/Code/RTradeLtd/s3x/cmd/api-errors.go:1801:cmd.toAPIErrorCode()
       3: /home/solidity/Code/RTradeLtd/s3x/cmd/api-errors.go:1826:cmd.toAPIError()
       2: /home/solidity/Code/RTradeLtd/s3x/cmd/object-handlers.go:414:cmd.objectAPIHandlers.GetObjectHandler()
       1: net/http/server.go:2012:http.HandlerFunc.ServeHTTP()

API: GetObject(bucket=bin, object=minio)
Time: 08:03:17 UTC 04/16/2020
DeploymentID: 4de3c0fa-4433-411e-ba95-38d53e0cf16e
RequestID: 16063E1946E4DD00
RemoteHost: 10.10.10.2
Host: 192.168.1.205:9999
UserAgent: MinIO (linux; amd64) minio-go/v6.0.50 mc/2020-03-14T01:23:37Z
Error: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4194309 vs. 4194304)
       4: /home/solidity/Code/RTradeLtd/s3x/cmd/api-errors.go:1801:cmd.toAPIErrorCode()
       3: /home/solidity/Code/RTradeLtd/s3x/cmd/api-errors.go:1826:cmd.toAPIError()
       2: /home/solidity/Code/RTradeLtd/s3x/cmd/object-handlers.go:414:cmd.objectAPIHandlers.GetObjectHandler()
       1: net/http/server.go:2012:http.HandlerFunc.ServeHTTP()

API: GetObject(bucket=bin, object=minio)
Time: 08:03:18 UTC 04/16/2020
DeploymentID: 4de3c0fa-4433-411e-ba95-38d53e0cf16e
RequestID: 16063E19929ADE4C
RemoteHost: 10.10.10.2
Host: 192.168.1.205:9999
UserAgent: MinIO (linux; amd64) minio-go/v6.0.50 mc/2020-03-14T01:23:37Z
Error: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4194309 vs. 4194304)
       4: /home/solidity/Code/RTradeLtd/s3x/cmd/api-errors.go:1801:cmd.toAPIErrorCode()
       3: /home/solidity/Code/RTradeLtd/s3x/cmd/api-errors.go:1826:cmd.toAPIError()
       2: /home/solidity/Code/RTradeLtd/s3x/cmd/object-handlers.go:414:cmd.objectAPIHandlers.GetObjectHandler()
       1: net/http/server.go:2012:http.HandlerFunc.ServeHTTP()
```

**Comment by bonedaddy** [comment]
Personally speaking I think the easiest solution is the stream based Dag RPC which will allow us to resolve this issue, and also enable using the Dag RPC for large DAG objects. This would be a fairly trivial change to the s3x codebase, as the semantic of using the Dag RPC would largely be the same. It's also a pretty minimal change to the TemporalX codebase.

If we agree on this solution @xiegeo I can get it done tomorrow

**Comment by bonedaddy** [comment]
Copying this here from discussion with @xiegeo:

It seems that we are already chunking data on upload, however we are slightly over-estimating chunk size and as a result metadata associated with puts the message size over the maximum. The best course of action appears to be the following:

s3x side:

* Reduce chunksize by 1-3% of maximum as a default
* Enable a CLI flag to set the default chunksize
* Use file API if we cant control max size (might not need to be done if we use the aforementioned configurable limit)

TemporalX side:

* If someone tries to upload an IPLD object larger than 4MB return an error and abort processiong

**Comment by xiegeo** [comment]
commit https://github.com/RTradeLtd/s3x/pull/40/commits/80055d9629d8aa0cb4c8744d51aa99d2c78bce02 contains an attempted fix.

**Comment by bonedaddy** [comment]
great work that fixed it
