### ISSUE TITLE
'mc admin' commands failing with wrong version found

### ISSUE THREAD

**Issue by perfectmak** [RTradeLtd/s3x#48]
## Expected Behavior

When I run an mc admin command like `mc admin info s3x`, it  should return the server information about the s3x target or at least invoke the correct `admin` service.

## Current Behavior

Currently any request to `mc admin` like `mc admin info s3x` or `mc admin config get s3x notify_webhook` always fails with an error message:

```
mc: <ERROR> Cannot get server '[notify_webhook]' config. Unexpected client 'admin' API version found 'v3', expected 'v2', please downgrade the client to older releases.
```

## Steps to Reproduce (for bugs)

1. Install the Minio Client `mc`.
2. Have a running instance of s3x using `./minio gateway s3x`
3. Set mc host using: `mc config host add s3x http://127.0.0.1:9000 minio miniostorage --api "s3v2"`
4. Run `mc admin info s3x`

## Context

I want to test out [minio bucket notification](https://docs.min.io/docs/minio-bucket-notification-guide.html) with s3x and to do that I need to invoke `mc admin config set...` to set it up properly.

## Regression
 No

## Your Environment

* Version used (`minio version`): RELEASE.2020-04-15T02-38-37Z
* Environment name and version (e.g. nginx 1.9.1): localhost (127.0.0.1:9000)
* Operating System and version (`uname -a`): 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
* Link to your project:

**Comment by bonedaddy** [comment]
I did some digging, because s3x is a minio gateway, as opposed to a minio server, I don't think this command will work. Digging through the `mc` documentation I see [this line](https://github.com/minio/mc/blob/master/cmd/admin-config-get.go#L43) which explicitly mentions `MinIO Server` now I'm not sure if this means that you need to run `minio server` to enable this functionality, however let me do some additional testing/research

**Comment by bonedaddy** [comment]
Yep, `mc admin` is only available for "MinIO Servers" and as this is a MinIO Gateway it wont work :( going to close this issue as there's  not much we can do about this except rewriting minio server to run s3x, which I don't think we will be doing

**Comment by perfectmak** [comment]
Okay. Thank you. I guess I'll find another way to get notifications on operations. Or is there a way you would recommend I do this?

**Comment by bonedaddy** [comment]
The only thing I can think of is if we perhaps define some sort of "Post Process Callback" function, that whenever a call is completed, if the callback is non nil then some action is performed.

For example https://github.com/RTradeLtd/s3x/blob/master/cmd/gateway/s3x/gateway-s3x.go#L45 could be extended to be:

```Go
type xObjects struct {
...omitted...
postProcessCallback func(args ...interface{})
}
```

Then for examlple in [`NewMultipartUpload`](https://github.com/RTradeLtd/s3x/blob/master/cmd/gateway/s3x/gateway-s3x-ledger-multipart.go#L30) we can have logic like


```Go
// NewMultipartUpload is used to store the initial start of a multipart upload request
func (ls *ledgerStore) NewMultipartUpload(multipartID string, info *ObjectInfo) error {
        defer func() {
            if ls.postProcessCallback != nil {
                ls.postProcessCallback(multipartID, info)
             }
       }()
	bucket := info.GetBucket()
	err := ls.assertBucketExits(bucket)
	if err != nil {
		return err
	}
	m := &MultipartUpload{
		ObjectInfo:  info,
		Id:          multipartID,
		ObjectParts: make(map[int64]ObjectPartInfo),
	}
	ls.pmapLocker.Lock()
	ls.l.MultipartUploads[multipartID] = m
	ls.pmapLocker.Unlock()
	data, err := m.Marshal()
	if err != nil {
		return err
	}
	return ls.ds.Put(dsPartKey.ChildString(multipartID), data)
}
```

But its probably best if a feature request is opened up to enable discuss the best way to go about implementing this
