### ISSUE TITLE
Delimiter functionality for ListObjects and ListObjectsV2 is not working

### ISSUE THREAD

**Issue by jsonsivar** [RTradeLtd/s3x#58]
## Expected Behavior
When using the `delimiter` field in a `ListObjectsV2` call, it should group the result by folders.

## Current Behavior
It's currently ignoring the delimiter field and not grouping the results by folder levels/prefix.

## Possible Solution
Both ListObjects and ListObjectsV2 [here](https://github.com/RTradeLtd/s3x/blob/master/cmd/gateway/s3x/gateway-s3x-object.go#L15) are ignoring the delimiter field.  So assuming the fix here is to take the result and do some parsing on it to group subfolder content by folders and serve that inside the `CommonPrefix` field.

## Steps to Reproduce (for bugs)
1. Create a bucket with a folder A inside and content in that folder
2. Create a subfolder B under folder A and and contents in there as well.
3. Call the list objects API using 
```
var AWS = require('aws-sdk');

var s3 = new AWS.S3({
  accessKeyId: 'minio',
  secretAccessKey: 'miniostorage',
  endpoint: 'http://localhost:9000',
... });

s3.listObjectsV2({
  Bucket: 'bucket-name',
  MaxKeys: 20,
  Delimiter: '/',
}, (err, data) => {
  console.log('res', err, data);
});
```
4. This does not use the delimiter field and the response is not grouped by folders.

## Context
We need to show folder context just for the cbuntu 18.04.3 LTS bionicurrent folder being browsed and this isn't possible without the delimiter field working.  It currently returns all files even in subfolders instead of just the current folder.

## Regression
No

## Your Environment
* Version used (`minio version`): [a85f85c](https://github.com/RTradeLtd/s3x/commit/a85f85cad79df7b60c746c8cd5ec637bc3385e1f) (HEAD -> master, tag: v0.0.7, origin/master, origin/HEAD)
* Environment name and version (e.g. nginx 1.9.1):  n/a
* Server type and version:  n/a
* Operating System and version (`uname -a`): Ubuntu 18.04.3 LTS bionic
* Link to your project: fleek.co

**Comment by storming0x** [comment]
Possible Fix , still undergoing some tests so may have more changes, but main idea seems to mimic current S3 API
https://github.com/FleekHQ/s3x/pull/6

**Comment by xiegeo** [comment]
@dmolina79 The link returns a 404 now, how did it go?

**Comment by storming0x** [comment]
hi @xiegeo sorry for the late response, we had to get creative on our end to move some things around and had to fork minio directly and put s3x gateway on top of it so we switched repos.
New repo is here. https://github.com/FleekHQ/minio

List directories with prefix works well here
https://github.com/FleekHQ/minio/blob/27a6976cd732c8f082e4874395d6b5a7c6aa809f/cmd/gateway/s3x/gateway-s3x-object.go#L43

we have it live on fleek so if that fix looks good we could prepare a PR for this issue. Although our current repo i think falls more in line what the intention of this project is to just support the s3x gateway layer. But yeah lmk.

**Comment by xiegeo** [comment]
@dmolina79 Thanks for the update, that switch makes sense. I refactored how we use minio here too, so make sure you check that out.

~~If you can, please submit a pull request. I'm working on a better implementation for ListObjects and ListObjectsV2 and would like to apply them on top of your changes. Otherwise, I'll just reference your code when implementing this feature.~~ see pull #75 

~~I'm not too sure how `maxkeys` should work with `CommonPrefix` field. Should the number of objects and `CommonPrefix` combined count to `maxkeys`, or count the number of objects covered in `CommonPrefix` too? The first option makes sense for how much data the client receives, the second makes sense for how much data the server processes.~~
