### ISSUE TITLE
A breaking change is coming, lets make the transition as seamless as possible!

### ISSUE THREAD

**Issue by xiegeo** [RTradeLtd/s3x#61]
The goal of this project is to add TemporalX support to minio, while the goal has not changed, the original approach has shown it's downsides. Maintains our fork with upstream has become a regular time sink, time we could use bug fixing and developing new features. So we are working towards reorganizing s3x only as a minio gateway instead of a full fork.

Removing the core minio code also gives us a chance to shink this repo if we rewrite master with a fresh history, ~~should this be done?~~ (yes)

Most of the work will be towards adopting the CI to concentrate on testing our gateway instead of minio as a whole.

With this change, what other breaking changes should we also make? What do you foresee that we should avoid breaking? Such as anything that we should avoid removing from s3x for your use cases.

This issue is to collect user feedback on this change, while #62 is for development.

**Comment by bonedaddy** [comment]
> The goal of this project is to add TemporalX support to minio, while the goal has not changed, the original approach has shown it's downsides. Maintains our fork with upstream has become a regular time sink, time we could use bug fixing and developing new features. So we are working towards reorganizing s3x only as a minio gateway instead of a full fork.

This will also probably make it much easier to port s3x upstream.

> Removing the core minio code also gives us a chance to shink this repo if we rewrite master with a fresh history, should this be done?

Yea I think so, since we just care about the gateway functionality rewriting history would give us a smaller codebase.

**Comment by xiegeo** [comment]
force push made
