### ISSUE TITLE
IPNS support for immutable share links

### ISSUE THREAD

**Issue by posix4e** [RTradeLtd/s3x#9]
**Is your feature request related to a problem? Please describe.**
When linking directories or files in IPFS, it's better to change the content without the link changing, You can use those URLs for downloads for smart contracts.

**Describe the solution you'd like**
We currently use IPNS so that way we can update the data under the hood and keep an immutable pointer to the directory. I wonder if you could take a similar approach with shared resources?

**Describe alternatives you've considered**
Just using s3!

**Comment by bonedaddy** [comment]
You can certainly use IPNS outside of the minio gateway to refer to the content that you store on IPFS via the gateway. However the issue with using IPNS within the gateway is that it is exceptionally slow, and the publish times would make using s3x as a backend unrealistic.

**Comment by posix4e** [comment]
Right, I was thinking just that, as part of the share download functionality

**Comment by bonedaddy** [comment]
Share download functionality? Could you explain more about this. I wasn't aware S3 had a method of sharing access to folders and objects

**Comment by posix4e** [comment]
I meant to enable https://docs.min.io/docs/minio-client-complete-guide#share


Share downloads

**Comment by bonedaddy** [comment]
ah i see thanks for the clarification, this is certainly something that we will look into
